### ISSUE TITLE
Not finding the slots correctly

### ISSUE THREAD

**Issue by yethendravarma** [SRvSaha/CoWinVaccineSlotFinder#19]
Hi,
I think the application is not finding the slots correctly. Getting notification from other sites that the slots were available but the application is not finding them even though it is running. It just keeps on fetching data. Tried with Both District search and Pincode search. But same issue

**Comment by SRvSaha** [comment]
Hi @yethendravarma, I hope you have done the config changes properly as per README.

Regarding Notification of Different Sites, most of them use Public APIs which have cached/stale data. So, probably results won’t be similar.

Now, if you feel slot in available and not being shown in this Application, try to login in the CoWIN Portal and then search for the same with the filter on Age, Vaccine Type, Vaccine Fee for the PIN/District and share the results wherever you are facing the inconsistency. 

Meanwhile we are working on the Debug Mode of the Application to help remote debug these kind of scenarios.

If possible share the config file’s setting by removing the mobile number and beneficiaries. I’ll debug it at my end and confirm!

**Comment by yethendravarma** [comment]
> Hi @yethendravarma, I hope you have done the config changes properly as per README.
> 
> Regarding Notification of Different Sites, most of them use Public APIs which have cached/stale data. So, probably results won’t be similar.
> 
> Now, if you feel slot in available and not being shown in this Application, try to login in the CoWIN Portal and then search for the same with the filter on Age, Vaccine Type, Vaccine Fee for the PIN/District and share the results wherever you are facing the inconsistency.
> 
> Meanwhile we are working on the Debug Mode of the Application to help remote debug these kind of scenarios.
> 
> If possible share the config file’s setting by removing the mobile number and beneficiaries. I’ll debug it at my end and confirm!


[appsettings.txt](https://github.com/SRvSaha/CoWinVaccineSlotFinder/files/6473010/appsettings.txt)
Hi @SRvSaha ,
Thank you Debug mode would help. Please find my settings file attached as text file.

**Comment by SRvSaha** [comment]
Hi @yethendravarma, I have checked the config file and it seems like the config you are having is a bit old.  But still it should work.
So, we need some more information:

1. What is the release version you are using? Can you please try the same with the latest release as well.
2. We need to know what is your System's Date Format set?  You can get the information from  Settings - > Time & Language -> Region.  It'd be somewhat like  ![this](https://user-images.githubusercontent.com/13312352/118140889-6ddeb180-b426-11eb-850f-cfaccc13d4d4.png) or this: 
![Full Image](https://user-images.githubusercontent.com/13312352/118140985-851d9f00-b426-11eb-9161-54f0b7fd8d77.png). 

If you feel that the format of your System's Short Date is not DD-MM-YYYY, then that is where the issue lies and we have already fixed it in Release Tag [v2.3.1-x86]( https://github.com/SRvSaha/CoWinVaccineSlotFinder/releases/tag/v2.3.1-x86)

**Comment by yethendravarma** [comment]
Hello @SRvSaha ,

The Version I have been using is your latest version updated last night 'CoWinReleasesv2.3.0-x64'. Ya I have been using the old settings file only since I don't see much changes in the new version apart from the format.(Will update this as well)
Regarding the system time I don't think that matters as I am using the latest version but I have cross checked it and below is the format and it is inline with the application.
![image](https://user-images.githubusercontent.com/33151368/118143280-cadb6700-b428-11eb-9ad0-9a4243346be2.png)

**Comment by SRvSaha** [comment]
Hi @yethendravarma, I have checked your scenario and seems like the config will not create any issue for v2.3.0. 
However, to test the scenario locally, I have a previously built v2.2.0-Debug Mode alpha release. It'll get the job done and then you'll need to do some manual filter to see why results are not coming for you.

Can you please share your gmail email address so that I can share with you the Alpha Release of Debug that'd help in identifying the root cause of the issue?

**Comment by yethendravarma** [comment]
Hi @SRvSaha ,

Sure below is my id
yethendravarma@gmail.com
will get back to you once I debug the issue.

**Comment by SRvSaha** [comment]
@yethendravarma As I can see, currently since the availablity is Zero, so you will not be shown any data in Normal Mode. In Debug Mode, it will show what is being returned. I guess that is what happened when you were searching as well.
Since I don't have the logs, can't be sure. That's a new feature to be added and will be there in New Release.

**Comment by SRvSaha** [comment]
In Case, I could help you, feel free to Star the repo and share it with your buddies! Also share your feedback by comment/share/like in the associated [ LinkedIn Post](https://www.linkedin.com/feed/update/urn:li:activity:6796093424492720128/) That'll be used as References/Testimonials in the Application and will increase the credibility of the App. @yethendravarma

**Comment by SRvSaha** [comment]
@PSuyog97 Please start working on the DEBUG Mode of the Application.
By Default, Logging Level of the Application to be set as INFO, when user switches to DEBUG Mode, log level is changed to DEBUG and there will be detailed logs (without logging user's personal information)

**Comment by yethendravarma** [comment]
@SRvSaha I have tried using the debug version and didnt find any issue. Not sure why the captcha didn't popup while running 'CoWinReleasesv2.3.0-x64' version but I saw it in debug mode version. Looking forward for the updated version where we can use the app in debug mode if required. I am closing this issue as the application is working as designed. Kudos to your application and efforts.

**Comment by SRvSaha** [comment]
Hi @yethendravarma, thanks for your time. Captcha might have been shown but the captcha window might not have been in focus. Also, another possibility is that getting the captcha image too long time so, till then captcha didn’t get displayed! A new version of Release v3.0.0 has been launched fox fixing certain captcha issue, please try with that once. Meanwhile we’ll be try hard to release the dubug mode feature in v3.1.0 or v3.2.0. In Case, I could help you, feel free to Star the repo and share it with your buddies! Also share your feedback by comment/share/like in the associated LinkedIn Post (https://www.linkedin.com/feed/update/urn:li:activity:6796093424492720128/) That'll be used as References/Testimonials in the Application and will increase the credibility of the App.

**Comment by SRvSaha** [comment]
Version 4.0.0 is out now. Thanks for your patience. Check it out: https://github.com/SRvSaha/CoWinVaccineSlotFinder/releases/latest
@yethendravarma @AkulRastogi
