### ISSUE TITLE
Auto Read OTP from

### ISSUE THREAD

**Issue by akshay8043** [SRvSaha/CoWinVaccineSlotFinder#28]
The Auto Read OTP using IFTTT feature works perfectly and automatically working from bombardier repo.

Do you think you can merge your code from https://github.com/bombardier-gif/covid-vaccine-booking for auto read OTP?

and compile it for windows?

**Comment by SRvSaha** [comment]
Hi @akshay8043, I think I can integrate IFTTT Feature. However I think I won't be building a separate Android App as Listener. Let's see how it can be done; Needs little bit of exploration. The repo you mentioned has done it already, since it is a bit difficult to set up for End User, I am checking if this can be a bit easier to do.
Shall be taken up ASAP.

**Comment by abhijeetsingh26** [comment]
Another way of getting the OTP read automatically can be google messages https://messages.google.com/web/authentication.
The only thing user needs to do is to set the "Messages" app as the default in the android phone and then open up using the link just like whatsapp web. Each conversation has its own ID and a unique URL.

Now this works well for applications running directly in the browser but I am not sure what tools are available in .NET to be able to manage a requirement like that.

**Comment by SRvSaha** [comment]
@abhijeetsingh26 Thanks for the suggestion, shall look into that.
Probably, if there is any way to write the OTP to some file in the filesystem using JS or any other thing from browser, it would work from .NET

**Comment by deepak-batra** [comment]
I'm using a combination of Telegram + IFTTT to do the auto OTP read work(though all of that is in python). 

The workflow:

1. Any message containing OTP and cowin can be forwarded to a channel in Telegram where @IFTTT bot is an admin. 
2. The forwarding is done by building an IFTTT applet. 
2. Read the telegram channel using the async python apis (Telethon) and read that in the code. (Simple producer/consumer pattern)

**Comment by SRvSaha** [comment]
@deepak-batra Thanks for the input. Do you mind working for the IFTTT part, I can do the integration with Telegram API.
Just a few questions: 1. How much latency do you observe in Auto OTP? In general, I feel users are able to type within 1/2 seconds. If latency is less than that, it'd be great. Would be grateful if you can help setup IFTTT and create a README Entry for that.

**Comment by deepak-batra** [comment]
A free IFTTT account generally runs the applet in typically 10s(although I've seen it to work in a sec many times). The paid version is supposed to be better but I don't know. 
I'm logged-in throughout the day(searching for covaxin) and i do mind typing in the OTP every 15 mins, so for me this setup works fine. 

Caveat:
Solution 1: We can create 1 public channel and ask users to have their name/something unique to them embedded in the message so that they know it's their OTP. 
Solution 2: Every user makes their own telegram channel and gives that in the config. (This is better as it doesn't have the common fate problem and privacy is taken care of.)  

Sure. I'll add the IFTTT stuff to Readme. 👍

**Comment by debanshur** [comment]
One simple hack would be to forward the OTP message from mobile to any mail address and then read it from there. 
For forwarding messages, already decent apps are available. Though Latency is there around 1-2 sec, this helps to be logged in throught the day. And if Auto Captacha can be done, then it becomes completely autonomous.

**Comment by SRvSaha** [comment]
Hi @debanshur thanks for the idea! Shall check out! AutoCaptcha is now live with v4.1.0, have a look!

**Comment by debanshur** [comment]
Yes, just checked it out. Works cool.
Can you share the resource for the lookup map implemented here for learning captcha

**Comment by SRvSaha** [comment]
> 
> 
> Yes, just checked it out. Works cool.
> Can you share the resource for the lookup map implemented here for learning captcha

Thanks debanshur! Please star the repo so that it'll be easier to get noticed when someone is searching!
I had used a pre-trained Model, so won't be able to help with that buddy!

**Comment by jayeshp004** [comment]
> I'm using a combination of Telegram + IFTTT to do the auto OTP read work(though all of that is in python).
> 
> The workflow:
> 
> 1. Any message containing OTP and cowin can be forwarded to a channel in Telegram where @IFTTT bot is an admin.
> 2. The forwarding is done by building an IFTTT applet.
> 3. Read the telegram channel using the async python apis (Telethon) and read that in the code. (Simple producer/consumer pattern)

how to do this ??

**Comment by deepak-batra** [comment]
> how to do this ??
You can have a look at this PR. I've updated the Readme.md for the same. lmk of any errors.

**Comment by SRvSaha** [comment]
Reason: #68
