### ISSUE TITLE
Captcha Model Encrypted Trained Model and Secret Key

### ISSUE THREAD

**Issue by nileshruby** [SRvSaha/CoWinVaccineSlotFinder#52]
Hello @SRvSaha ,
After taking latest while book slot error comes:
public const string ENCRYPTED_TRAINED_MODEL = "YOUR_TRAINED_MODEL_HERE";
        public const string SECRET_KEY = "YOUR_MODEL_DECRYPTION_KEY";
Can you please help me with what value need to pass here?

![image](https://user-images.githubusercontent.com/6216633/118975209-64f36000-b991-11eb-9f66-70f4253dfc10.png)

Thanks.

**Comment by SRvSaha** [comment]
Hi @nileshruby Sorry those are kind of confidential data and hence stored securely.

You don't need to run the App using Visual Studio, download the latest release from here : [v4.1.0](https://github.com/srvsaha/CoWINVaccineSlotFinder/releases/latest) and just run the Exe. That's it.

All the heavy-lifting is already done and you don't need explicit dependencies to run the App.

Enjoy! Also, please star the repo so that it can come higher in search ranking and reach out to many people and help them.

**Comment by nileshruby** [comment]
But where you have put this as I don't see in the project and gives me an error while available slots trying to book a slot.
Thanks.

**Comment by SRvSaha** [comment]
> 
> 
> But where you have put this as I don't see in the project and gives me an error while available slots trying to book a slot.
> Thanks.

Drop me an email, I'd be happy to share you the sought data.

**Comment by AnmolGupta83** [comment]
Hi @SRvSaha ,

I really would appreciate your work done here. Great work done !!!!! but I'm also facing same issue for 
ENCRYPTED_TRAINED_MODEL = "YOUR_TRAINED_MODEL_HERE";
public const string SECRET_KEY = "YOUR_MODEL_DECRYPTION_KEY";

so is it something I can not edit the code as per my requirement and execute it, and I should be using only release exe? or I misunderstood?

**Comment by SRvSaha** [comment]
Hi, @AnmolGupta83, Thanks.
You can edit the code as per your requirement.
Since now there is no requirement for Captcha, you won't need these.

Since it is not a good practice to hard-code confidential information in source code, so you'll get this kind of placeholders. You can ignore it, take the latest version and go ahead make your changes. 

Release is a good way since dependencies are bundled, since you want to do it through Code, you can do, no issues with that
