### ISSUE TITLE
Can't connect to the server for this app

### ISSUE THREAD

**Issue by Tnu02** [SRvSaha/CoWinVaccineSlotFinder#53]
![App](https://user-images.githubusercontent.com/83922100/119084404-5b183e00-ba1f-11eb-8528-e7bd01100752.jpg)

not sure why started getting this error.

**Comment by SRvSaha** [comment]
Hi @Tnu02, this error comes when you are reaching the throlling limit of the IP for CoWIN.
Make sure you keep a Interval of 5000 ms so that this doesn't come. Or else try after some time, it'd work.

**Comment by 5HU8H** [comment]
@SRvSaha I'm getting this error even after keeping the interval to 10000ms. I've tried 5000ms, 8000ms and now 10000ms and all of them are giving me this error. And I'm searching all of Delhi's districts. Any solution?

**Comment by SRvSaha** [comment]
@5HU8H I think they had added stringent IP Throttling. Similar issues have been raised here as well. 


I am trying to see if I can get any fix. The only solution as of now is changing the interval and stopping and trying after sometime, or to use multiple IP Addresses based machine.

**Comment by slomogangsta** [comment]
Seems like an issue with Co-WIN API itself
![image](https://user-images.githubusercontent.com/42892043/119225503-be8a9480-bb21-11eb-9173-d4813bbd1534.png)

**Comment by SRvSaha** [comment]
@slomogangsta Yeah there has been some issue reported regarding handling of sessions in CoWIN. I too felt the same.
Now there is some throttling issue that is going on.

**Comment by saurabhkrr** [comment]
hey have you found any fix ? there's no effect of increasing interval

**Comment by SRvSaha** [comment]
@saurabhkrr The Rate Limit as I feel by observation is 100 Hits from IP within 5 minutes. 
So, if you are searching for 1 PIN Code then you'll have to keep the SleepInterval as 3000, similarly if you have 2 PIN Codes, it will be 6000 and so on and so forth so that IP is within the rate limit. Another way out is to use two different network IPs and then keep switching between the once you see the error. You can copy the Bearer Token you get after entering OTP, and then on subsequent run from different IP. you have use that in the config file so that re-OTP is not required. This the only work around as of now. Also, try varying the User Agent, might help.

**Comment by PSuyog97** [comment]
@SRvSaha Need to change sleep interval time based on the number of PIN codes.

**Comment by saurabhkrr** [comment]
i tried running it with only one pin code... still the ip is getting blocked

**Comment by Tnu02** [comment]
@SRvSaha it's very strange but it started showing slot for 45+ as sson as the slot got opened. With lable [INFO] Sorry! No slot available for search critiera: Age 18-45 - Pin and showing all the 45+ accounts

**Comment by SRvSaha** [comment]
@saurabhkrr  So, if you are searching for 1 PIN Code then you'll have to keep the SleepInterval as 3000, similarly if you have 2 PIN Codes, it will be 6000 and so on and so forth so that IP is within the rate limit. Another way out is to use two different network IPs and then keep switching between the once you see the error. You can copy the Bearer Token you get after entering OTP, and then on subsequent run from different IP. you have use that in the config file so that re-OTP is not required. This the only work around as of now. Also, try varying the User Agent, might help.

**Comment by saurabhkrr** [comment]
1 pin code with 3000 sleep interval.. nothing's working

**Comment by SRvSaha** [comment]
Try with 5000 or higher and if possible keep switching IPs. This is not just us, everyone is impacted because of the IP Throttling. @saurabhkrr

**Comment by SRvSaha** [comment]
@saurabhkrr @Tnu02 Release [v4.2.0](https://github.com/SRvSaha/CoWinVaccineSlotFinder/releases/latest) is up now. Check it out and share your feedback. This release tries to address some of the issue of IP Throttling.

**Comment by saurabhkrr** [comment]
![Uploading IMG20210523183406.jpg…]()

**Comment by saurabhkrr** [comment]
![Uploading IMG20210523183406.jpg…]()

**Comment by SRvSaha** [comment]
@saurabhkrr The image is not visible, can you reshare
