### ISSUE TITLE
Question - Are you gonna release a software version after 4.1.0?

### ISSUE THREAD

**Issue by xxxAng** [SRvSaha/CoWinVaccineSlotFinder#57]
Are you gonna release a software version now because header and throttling issues got fixed already?
And it is convenient for most of people to run from EXE.

**Comment by SRvSaha** [comment]
Yes, I am gonna release a v4.2.0 today. Stay tuned @xxxAng 
Issue are resolved partially actually, since there is no proper way to by-pass throlling rather than using Proxy Servers or TOR or VPN or different networks. We are trying out best to handle the scenario gracefully and maximizing the chances of booking without getting ban.

**Comment by SRvSaha** [comment]
@xxxAng Release [v4.2.0](https://github.com/SRvSaha/CoWinVaccineSlotFinder/releases/latest) is up now. Check it out and share your feedback. Thanks for your patience.
