### ISSUE TITLE
Too many hits from IP address

### ISSUE THREAD

**Issue by Krishnakumar1007** [SRvSaha/CoWinVaccineSlotFinder#60]
How can we resolve this issue of too many hits from IP address? Any pointers?

**Comment by SRvSaha** [comment]
@Krishnakumar1007 This is because CoWIN has introduced IP Throttling. 
Short term issue resolution technique is to use two different networks and then once you get this error switch to another and back and forth.
You can check out the related issue for more details: #53

**Comment by akshay8043** [comment]
![image](https://user-images.githubusercontent.com/32493756/119266424-64183380-bc08-11eb-9fc4-11fea1d470a3.png)

Hi @SRvSaha ,

Saw the above issue on comment #53 Do you think we can use any proxy to bypass the IP blacklisting.

Can you confirm if this issue persists for version 4.1?

Can you tell when they have started the IP throttling?

**Comment by SRvSaha** [comment]
@akshay8043 Yes, you can bypass using any proxy server provided you have 3/4 proxy servers. Or simple way would be to try from 2/3 IPs.
Another way around is to try using some VPN. See what works for you.

The issue is not specific to this version. They havw added throttling from yesterday and hence all version and all applications for that matter will face the same issue.

**Comment by saurabhkrr** [comment]
so if ip throttling is added from yesterday ..how come these alert bots are not effected by it

**Comment by SRvSaha** [comment]
@saurabhkrr It's simple, the bots might not be hosted in system with single IP. Let's say a bot is hosted in cloud in N number of Virtual Machines, all having different IP Addresses, they can still notify you without getting throttled. Challenge comes when the number of PIN/Districts for which the Bot is searching increases. So, suggestion would be to use multiple networks, else rely on the notification of the bots and then book! Either way you are through

**Comment by SRvSaha** [comment]
@akshay8043 @saurabhkrr Check this https://github.com/bombardier-gif/covid-vaccine-booking/issues/288

**Comment by saurabhkrr** [comment]
![IMG_20210524_090604](https://user-images.githubusercontent.com/76863660/119293161-724d6a80-bc6f-11eb-8ffd-e099760545af.jpg)

**Comment by saurabhkrr** [comment]
at try#3 there was 4 hospitals and at try#5 a slot came but it got fully booked... increasing sleep interval is not helping

**Comment by SRvSaha** [comment]
@saurabhkrr See, this is like a trade-off we have to do, that's why we have made it configurable. Let's say you know that stop will come at 9 am and get notified using some notifier like U45 Telegram Group, then you can turn off the IPThrottling from the Config file by setting `"IsThrottlingToBeUsed": false`
You can even change the default sleep time to `"SleepIntervalInMilliseconds": 1000` so that it runs every 1 second. 

This will help you do the booking provided you know when slots will come since you will be making too many requests from your IP. Also, keep another network/proxy server, from where you can search, so that you have multiple networks and when 1 IP is banned, you use the other one and so on and so forth

**Comment by SRvSaha** [comment]
Cross Platform Support is enabled with Version 5.0.0 Release.

Linux: https://github.com/SRvSaha/CoWinVaccineSlotFinder/releases/tag/v5.0.0-linux
Mac: https://github.com/SRvSaha/CoWinVaccineSlotFinder/releases/tag/v5.0.0-osx
Windows: https://github.com/SRvSaha/CoWinVaccineSlotFinder/releases/tag/v5.0.0-windows
