### ISSUE TITLE
Getting System.IO.InvalidDataException at Decrypt method

### ISSUE THREAD

**Issue by lakshaykaura** [SRvSaha/CoWinVaccineSlotFinder#70]
Just before booking the slot it breaks. And no slot gets booked.
Request you to please help in running this.
![image](https://user-images.githubusercontent.com/53444913/120061566-774d5800-c07b-11eb-89a4-5dbe6718844e.png)

**Comment by lakshaykaura** [comment]
Same issue is there in latest master and in v4.2.0 as well.
Could you please let us know when we can expect this to be fixed or how to fix it?

**Comment by SRvSaha** [comment]
@lakshaykaura Please use the App from the Release Version.
You are getting the Error since the Code doesn't have the secrets embedded in them. Either you get the secrets for yourself and replace them in the file, else you the Release Version.

**Comment by lakshaykaura** [comment]
Hi I am using release version only v4.2.0

**Comment by SRvSaha** [comment]
@lakshaykaura Yes please try with the EXE since it has everything in it and you don't need any dependencies. Just a double click.
Since you are curious to know the reason of the error, see this: https://github.com/SRvSaha/CoWinVaccineSlotFinder/blob/master/CoWin.Core/Models/CaptchaModel.cs

Basically you can put Encrypted Model with Base64 encoding along with the Secret Key. You'll then be able to use it from Visual Studio as well. Hardcoding those details in Code ain't good practice.

**Comment by lakshaykaura** [comment]
Alright! That explains. So I am using exe now. Hopefully it will not fail :)
Btw Thankyou @SRvSaha so much for such an awesome app.

**Comment by SRvSaha** [comment]
@lakshaykaura Yep that will work without fail, don't worry! Thanks for using it. Happy to help! Please share it in your circles and help the needy to get slots. Let me know if you could book your slot. You may like to share your testimonial/feedback here: https://shawt.io/r/sYx

**Comment by lakshaykaura** [comment]
With latest exe I am getting this error now-
![image](https://user-images.githubusercontent.com/53444913/120062312-25a6cc80-c07f-11eb-8259-8344a8fa576d.png)
Even though throttling is off, refresh time is 40000ms which is like 7-8 requests in 5min. Even if it count one request per district then also I am searching in 2 so total of max 16 requests in 5min which is way less than 100 requests in 5min limit. Could you please help on how to fix this?

**Comment by SRvSaha** [comment]
@lakshaykaura `IsThrottlingToBeUsed` to be set to true, it is to be kept false only when CoWIN has removed Throttling from APIs. If it is set to false, then it will by default take 40 sec as sleep time between any subsequent API calls which looks okay to me. TBH, the Rate Limiting implemented by them is buggy so this happens. Also, another this is, since your public IP Address is shared and let's say you are using your phone as well as the Software to make requests, all will be counted towards 100. Also since your IP is shared with lets say 5 people, even their hits will be counted for 100/5 mins. 
Caveat is, the rate limiting is checked in sliding window of 30 seconds and therefore you can just close the App whenver you get IP Throttled and restart after 10/15 seconds. Your authentication is taken care of so you won't need OTP unless 15 minutes is over. So you can keep closing and re-starting the App without any issues.

**Comment by betagoyal** [comment]
Hey , I am using 4.1 release. Its works for me very well . I dont want to use 4.2 version bcs of many reason.

But i want that IsSearchToBeDoneForVaccinationCentreName": true, feature.
Is it possible ?

**Comment by betagoyal** [comment]
dont need throttling stuff bcs i have multiple IP

**Comment by SRvSaha** [comment]
@betagoyal Good to know that version 4.1.0 works pretty well for you.
Now coming to the question of `IsSearchToBeDoneForVaccinationCentreName` option, well there is no backward compatibility for the feature.

Secondly whatever you could do with v4.1.0, you can even do with v4.2.0. You need to turn off the throttling and set `SleepInterveralInMilliseconds` to 2000 and then it will work as v4.1.0 only. And when your IP gets throttled you can keep on switching your IPs since you are telling you multiple IP Addresses. 

Hope this addresses your query! Grateful if you star the repo if I could help!

**Comment by betagoyal** [comment]
In 4.1 release when an IP gets block i switch to another IP thats all. I need not to close running instance .
In 4.2 i have to close that instance, change ip  and then i re run exe file again . Its a headache and one more thing in 4.1 release an IP works longer then 4.2 .
4.2 version have to run again n again . Its not that peaceful .
I think its not hard for u .
I can attach SS

**Comment by betagoyal** [comment]
As u suggest I turned  off throttling and tried like you said . But it does not work

**Comment by SRvSaha** [comment]
@betagoyal The Application needs to be re-started as of now. There is no other option, but re-starting  hardly takes 1 second since you don't need to enter your OTP or anything. I will check if something can be done so that user gets an option to either exit the application or continue by pressing any key.

Throttling will be there in both versions. Just the thing is you need to change IP or try after 10 seconds. That's not in my hand.

**Comment by betagoyal** [comment]
@SRvSaha Thanks for considering problem. try to resolve with 4.2 .
AND BCS OF YOU MY WHOLE FAMILY VACCINATED .
**THANK YOU
THANK YOU
THANK YOU**

**Comment by lakshaykaura** [comment]
@SRvSaha any list of error codes and their description? Got below three times today for different centers-
![image](https://user-images.githubusercontent.com/53444913/120069174-1a18cd00-c0a2-11eb-814b-0adbbaa94ec8.png)

**Comment by SRvSaha** [comment]
> 
> 
> @SRvSaha Thanks for considering problem. try to resolve with 4.2 .
> AND BCS OF YOU MY WHOLE FAMILY VACCINATED .
> **THANK YOU THANK YOU THANK YOU**

Hi, Feature shall be a part of v5.0.0

Glad that I could help. Star the Repo and share with others so that they can also get vaccinated.

**Comment by SRvSaha** [comment]
> 
> 
> @SRvSaha any list of error codes and their fixes? Got below three times today for different centers-
> ![image](https://user-images.githubusercontent.com/53444913/120069174-1a18cd00-c0a2-11eb-814b-0adbbaa94ec8.png)

There is no such list of available, basically the Error is coming as the Slot which you were trying to book got already booked till the time you tried, since 100s of people are trying for very limited seats.

**Comment by betagoyal** [comment]
New update works like charm . Now i have stared the repo.

**Comment by SRvSaha** [comment]
@betagoyal Awesome! Glad that you liked it. Share it with others as well so that it can be of help!

**Comment by SRvSaha** [comment]
@betagoyal @lakshaykaura Can you please test the scenario as per the description in #79 in your machine and see if it works. Need some feedback that it works, before making a new release. See the discussions for all different types of test scenarios. Would be happy if you can contribute.

**Comment by betagoyal** [comment]
@SRvSaha i am already on it ..will get back to you soon
