### ISSUE TITLE
Co-WIN API Integration and Production access

### ISSUE THREAD

**Issue by aman-3003** [SRvSaha/CoWinVaccineSlotFinder#81]
@SRvSaha Check this out : https://sandbox.ndhm.gov.in/cowin/

**Comment by 520rahul** [comment]
@SRvSaha it looks like public api vill not b a much help in coming days

**Comment by Tnu02** [comment]
Any progress guys.. !!

**Comment by SRvSaha** [comment]
Yeah! Probably this is the last release. Repo might be taken down as well (not sure) #68
Version 5.2.0 is out now will all the fixes suggested here and #79 along with new features for better UX. Thank you for your patience and support. Check it out and share your feedback!

**Comment by 520rahul** [comment]
@SRvSaha thanks for version 5.2. And plz dont take down this repo and developments in the same.  Because of you we are able to get vaccinated and able to help lots of friends, families, servents who r not very much educated or have no internet access, u have done wonderfull work boss. Plz keep going. All d best. We all need u
