### ISSUE TITLE
How can i use telegram bot model ? Is it reads otp and send to script through bot ?

### ISSUE THREAD

**Issue by PATTOOo** [SRvSaha/CoWinVaccineSlotFinder#89]
https://github.com/SRvSaha/CoWinVaccineSlotFinder/blob/master/CoWin.Core/Models/TelegramBotModel.cs
how i can setup this or use this. Please help

**Comment by SRvSaha** [comment]
@PATTOOo No, the Telegram Bot Model is just to send you notification that the booking has been done. OTP has not been automated as there are limits on number of OTPs you can requests before getting blocked from CoWIN.

To Setup the TelegramBot, you can get your token from Bot Father, add the ChatId where you want to notify when booking is done and the secret is used for decrypting of the Token of your Telegram Bot.

In case you are just looking for booking, rather than going the hard way, you can use the Release Version, it will work fine.
