### ISSUE TITLE
Slot searching new feature

### ISSUE THREAD

**Issue by 520rahul** [SRvSaha/CoWinVaccineSlotFinder#91]
There r many districts where online slots timing is not fixed and slots r uploaded on random basis and sometimes telegram channels also dont notify the same and v miss the slot, therefore it is not possible for keep login in 15 minutes for slots checking. I was thinking can u make a optional feature of checking slots without login and when the repo find out a desired slot it automatically sends otp to the mobile no. By this our login attempts can be saved and and v can run the repo for longer time without any problem. But plz keep this feature as optional and not mandatory for everone, as inserting otp takes time so for the districts where slot uploading time is fixed and v know the exact timing in that case we can use current version of repo

**Comment by SRvSaha** [comment]
@520rahul Even now you can do this thing. Just keep the ProtectedAPI:IsToBeUsed as false.
However there are multiple issues why this is not feasible:

* When you keep on searching for long hours from one particular IP Address, your account might get block or your IP will get throttled and eventually blacklisted.

It's better you keep some using some service like http://vaccineslot.in/ where you can run for long hours in the browser and there will be no issues with IP Blocking or Rate Limiting or anything else.

It'll beep when slot is found and use the App to book. That's a better way rather than running the App in PC for long hours.
